version: '3'
services:

  nginx:
    restart: always
    image: nginx:1.13-alpine
    env_file:
      - .env
    command: /bin/sh -c "envsubst '$$SERVER_NAME $$APP_HOST $$STREAMING_HOST' < /etc/nginx/conf.d/nginx_mastodon.conf.template > /etc/nginx/conf.d/nginx_mastodon.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"
    volumes:
      - ./nginx_mastodon.conf.template:/etc/nginx/conf.d/nginx_mastodon.conf.template
      - /var/lib/mastodon/nginx/public:/usr/share/nginx/html
